spring:
  application:
    name: aws-secret-version-three-demo
  config:
    import: aws-secretsmanager:/secret/application-dev;
  cloud:
    aws:
      secretsmanager:
        enabled: true
        endpoint:
        region:
    cloud:
      aws:
        secretsmanager:
          reload:
            period: 2s
            max-wait-time-for-restart: 2s

management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

myconfig:
  eapi:
    user: ${secretuser}
    password: ${secretpassword}
    region: testregionddddddddddddfffff




